version: '3.8'

services:
  go_app:
    container_name: go_app
    image: products-api
    build: .
    ports:
      - "8000:8000"
    depends_on:
      mysql_db:
        condition: service_healthy

  mysql_db:
    container_name: mysql_db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: comerce
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
